import type { PracticeActivity, PracticeFeaturedMode } from "./practiceTypes";

export const FEATURED_MODES: PracticeFeaturedMode[] = [
  {
    id: "mode-listening",
    title: "Listening",
    subtitle: "Train your ear with short clips",
    emoji: "🎧",
    kind: "listening",
  },
  {
    id: "mode-pronunciation",
    title: "Pronunciation",
    subtitle: "Say it right, build confidence",
    emoji: "🗣️",
    kind: "pronunciation",
  },
  {
    id: "mode-daily-quiz",
    title: "Daily Quiz",
    subtitle: "A quick check-in every day",
    emoji: "🧠",
    kind: "daily-quiz",
  },
];

export const PRACTICE_ACTIVITIES: PracticeActivity[] = [
  {
    id: "p1",
    title: "Sound Match",
    description: "Hear a word and choose the correct meaning.",
    kind: "listening",
    emoji: "🎧",
    durationLabel: "3–5 min",
    xpLabel: "+10 XP",
    tags: ["listening", "audio", "comprehension", "words"],
  },
  {
    id: "p2",
    title: "Shadow Speaking",
    description: "Repeat after native audio and match rhythm.",
    kind: "pronunciation",
    emoji: "🗣️",
    durationLabel: "5–7 min",
    xpLabel: "+15 XP",
    tags: ["pronunciation", "speaking", "accent", "rhythm"],
  },
  {
    id: "p3",
    title: "Daily Quiz",
    description: "A mixed set of quick questions.",
    kind: "daily-quiz",
    emoji: "🧠",
    durationLabel: "2–4 min",
    xpLabel: "+12 XP",
    tags: ["daily", "quiz", "review", "mixed"],
  },
  {
    id: "p4",
    title: "Vocabulary Sprint",
    description: "Rapid-fire vocab checks to stay sharp.",
    kind: "vocabulary",
    emoji: "⚡",
    durationLabel: "4–6 min",
    xpLabel: "+12 XP",
    tags: ["vocabulary", "words", "review"],
  },
  {
    id: "p5",
    title: "Conversation Warm-up",
    description: "Practice common phrases in context.",
    kind: "conversation",
    emoji: "💬",
    durationLabel: "6–8 min",
    xpLabel: "+18 XP",
    tags: ["conversation", "phrases", "speaking"],
  },
  {
    id: "karaoke-lyrics",
    title: "Karaoke Lyrics",
    description: "Listen and follow along word-by-word.",
    kind: "listening",
    emoji: "🎶",
    durationLabel: "~10 sec",
    xpLabel: "+5 XP",
    tags: ["listening", "audio", "lyrics", "timed"],
  },
];
