import type { SeedLessonUnit } from "./unit-2";

export const UNIT_5_OCCUPATIONS_AND_PLACES_SW: SeedLessonUnit = {
  externalId: "unit-5",
  title: "Occupations and Places - Kazi na Maeneo",
  level: "absolute-beginner",
  icon: "🏢",
  color: "#00BCD4",
  xpReward: 50,
  order: 4,
  isActive: true,
  activities: [
    {
      externalId: "activity-occ-places-1",
      type: "introduction",
      question:
        "Let's learn about different occupations and important places in our community!",
      order: 1,
      componentKey: "unit5-introduction",
      contentRef: "activity-occ-places-1",
    },
    {
      externalId: "activity-occ-places-2",
      type: "vocabulary-table",
      question: "Common Places",
      order: 2,
      componentKey: "unit5-vocabulary-table",
      contentRef: "activity-occ-places-2",
    },
    {
      externalId: "activity-occ-places-3",
      type: "vocabulary-table",
      question: "Common Occupations",
      order: 3,
      componentKey: "unit5-vocabulary-table",
      contentRef: "activity-occ-places-3",
    },
    {
      externalId: "activity-occ-places-4",
      type: "multiple-choice",
      question: "Where would you find a 'Mwalimu'?",
      order: 4,
      componentKey: "unit5-multiple-choice",
      contentRef: "activity-occ-places-4",
    },
    {
      externalId: "activity-occ-places-5",
      type: "multiple-choice",
      question: "What is 'Hospitali' in English?",
      order: 5,
      componentKey: "unit5-multiple-choice",
      contentRef: "activity-occ-places-5",
    },
    {
      externalId: "activity-occ-places-6",
      type: "multiple-choice",
      question: "How do you say 'Doctor' in Swahili?",
      order: 6,
      componentKey: "unit5-multiple-choice",
      contentRef: "activity-occ-places-6",
    },
    {
      externalId: "activity-occ-places-7",
      type: "multiple-choice",
      question: "Where would you buy medicine?",
      order: 7,
      componentKey: "unit5-multiple-choice",
      contentRef: "activity-occ-places-7",
    },
    {
      externalId: "activity-occ-places-8",
      type: "spelling-completion",
      question: "Complete the Spelling of Places",
      order: 8,
      componentKey: "unit5-spelling-completion",
      contentRef: "activity-occ-places-8",
    },
    {
      externalId: "activity-occ-places-9",
      type: "spelling-completion",
      question: "Complete the Spelling of Occupations",
      order: 9,
      componentKey: "unit5-spelling-completion",
      contentRef: "activity-occ-places-9",
    },
    {
      externalId: "activity-occ-places-10",
      type: "matching",
      question: "Match Occupations to Their Workplaces",
      order: 10,
      componentKey: "unit5-matching",
      contentRef: "activity-occ-places-10",
    },
    {
      externalId: "activity-occ-places-11",
      type: "listening-dictation",
      question: "Listening Exercise: Places and Occupations",
      order: 11,
      componentKey: "unit5-listening-dictation",
      contentRef: "activity-occ-places-11",
    },
  ],
};
