import type { SeedLessonUnit } from "./unit-2";

export const UNIT_3_TIME_SW: SeedLessonUnit = {
  externalId: "unit-3",
  title: "Days, Months, and Seasons",
  level: "absolute-beginner",
  icon: "📅",
  color: "#9C27B0",
  xpReward: 50,
  order: 2,
  isActive: true,
  activities: [
    {
      externalId: "activity-time-1",
      type: "introduction",
      question:
        "Let's learn how to talk about days, months, and seasons in Swahili!",
      order: 1,
      componentKey: "introduction",
      contentRef: "activity-time-1",
    },
    {
      externalId: "activity-time-2",
      type: "vocabulary-table",
      question: "Days of the Week",
      order: 2,
      componentKey: "vocabulary-table",
      contentRef: "activity-time-2",
    },
    {
      externalId: "activity-time-3",
      type: "vocabulary-table",
      question: "Months of the Year",
      order: 3,
      componentKey: "vocabulary-table",
      contentRef: "activity-time-3",
    },
    {
      externalId: "activity-time-4",
      type: "vocabulary-table",
      question: "Seasons",
      order: 4,
      componentKey: "vocabulary-table",
      contentRef: "activity-time-4",
    },
    {
      externalId: "activity-time-5",
      type: "multiple-choice",
      question: "What day comes after 'Jumanne'?",
      order: 5,
      componentKey: "multiple-choice",
      contentRef: "activity-time-5",
    },
    {
      externalId: "activity-time-6",
      type: "multiple-choice",
      question: "Which month is 'Machi'?",
      order: 6,
      componentKey: "multiple-choice",
      contentRef: "activity-time-6",
    },
    {
      externalId: "activity-time-7",
      type: "multiple-choice",
      question: "What is the Swahili word for Friday?",
      order: 7,
      componentKey: "multiple-choice",
      contentRef: "activity-time-7",
    },
    {
      externalId: "activity-time-8",
      type: "spelling-completion",
      question: "Complete the Days of the Week",
      order: 8,
      componentKey: "spelling-completion",
      contentRef: "activity-time-8",
    },
    {
      externalId: "activity-time-9",
      type: "spelling-completion",
      question: "Complete the Months of the Year",
      order: 9,
      componentKey: "spelling-completion",
      contentRef: "activity-time-9",
    },
    {
      externalId: "activity-time-10",
      type: "multiple-choice",
      question: "What is 'Jumapili'?",
      order: 10,
      componentKey: "multiple-choice",
      contentRef: "activity-time-10",
    },
    {
      externalId: "activity-time-11",
      type: "multiple-choice",
      question: "Which season is 'Masika'?",
      order: 11,
      componentKey: "multiple-choice",
      contentRef: "activity-time-11",
    },
    {
      externalId: "activity-time-12",
      type: "matching",
      question: "Match Days to English",
      order: 12,
      componentKey: "matching",
      contentRef: "activity-time-12",
    },
    {
      externalId: "activity-time-13",
      type: "matching",
      question: "Match Months to English",
      order: 13,
      componentKey: "matching",
      contentRef: "activity-time-13",
    },
    {
      externalId: "activity-time-14",
      type: "listening-dictation",
      question: "Listening Exercise: Days and Months",
      order: 14,
      componentKey: "listening-dictation",
      contentRef: "activity-time-14",
    },
    {
      externalId: "activity-time-15",
      type: "conversation-practice",
      question: "Practice Talking About Days",
      order: 15,
      componentKey: "conversation-practice",
      contentRef: "activity-time-15",
    },
    {
      externalId: "activity-time-16",
      type: "dialogue",
      question: "Planning a Meeting",
      order: 16,
      componentKey: "dialogue",
      contentRef: "activity-time-16",
    },
  ],
};
