import type { SeedLessonUnit } from "./unit-2";

export const UNIT_7_COLORS_SW: SeedLessonUnit = {
  externalId: "unit-7",
  title: "Colors - Rangi",
  level: "absolute-beginner",
  icon: "🎨",
  color: "#E91E63",
  xpReward: 100,
  order: 6,
  isActive: true,
  activities: [
    {
      externalId: "activity-colors-1",
      type: "introduction",
      question:
        "Let's learn about colors in Swahili! Colors help us describe the world around us.",
      order: 1,
      componentKey: "unit7-introduction",
      contentRef: "activity-colors-1",
    },
    {
      externalId: "activity-colors-2",
      type: "vocabulary-table",
      question: "Basic Colors",
      order: 2,
      componentKey: "unit7-vocabulary-table",
      contentRef: "activity-colors-2",
    },
    {
      externalId: "activity-colors-3",
      type: "vocabulary-table",
      question: "Neutral Colors",
      order: 3,
      componentKey: "unit7-vocabulary-table",
      contentRef: "activity-colors-3",
    },
    {
      externalId: "activity-colors-4",
      type: "multiple-choice",
      question: "What is 'Nyekundu' in English?",
      order: 4,
      componentKey: "unit7-multiple-choice",
      contentRef: "activity-colors-4",
    },
    {
      externalId: "activity-colors-5",
      type: "multiple-choice",
      question: "How do you say 'Green' in Swahili?",
      order: 5,
      componentKey: "unit7-multiple-choice",
      contentRef: "activity-colors-5",
    },
    {
      externalId: "activity-colors-6",
      type: "multiple-choice",
      question: "What color is 'Nyeupe'?",
      order: 6,
      componentKey: "unit7-multiple-choice",
      contentRef: "activity-colors-6",
    },
    {
      externalId: "activity-colors-7",
      type: "multiple-choice",
      question: "How do you say 'Purple' in Swahili?",
      order: 7,
      componentKey: "unit7-multiple-choice",
      contentRef: "activity-colors-7",
    },
    {
      externalId: "activity-colors-8",
      type: "multiple-choice",
      question: "What is 'Rangi ya chungwa'?",
      order: 8,
      componentKey: "unit7-multiple-choice",
      contentRef: "activity-colors-8",
    },
    {
      externalId: "activity-colors-9",
      type: "spelling-completion",
      question: "Complete the Color Names",
      order: 9,
      componentKey: "unit7-spelling-completion",
      contentRef: "activity-colors-9",
    },
    {
      externalId: "activity-colors-10",
      type: "matching",
      question: "Match Colors to Their Meanings",
      order: 10,
      componentKey: "unit7-matching",
      contentRef: "activity-colors-10",
    },
    {
      externalId: "activity-colors-11",
      type: "listening-dictation",
      question: "Listening Exercise: Write the Colors",
      order: 11,
      componentKey: "unit7-listening-dictation",
      contentRef: "activity-colors-11",
    },
    {
      externalId: "activity-colors-12",
      type: "conversation-practice",
      question: "Practice Describing Colors",
      order: 12,
      componentKey: "unit7-conversation-practice",
      contentRef: "activity-colors-12",
    },
    {
      externalId: "activity-colors-13",
      type: "dialogue",
      question: "Shopping for Clothes",
      order: 13,
      componentKey: "unit7-dialogue",
      contentRef: "activity-colors-13",
    },
    {
      externalId: "activity-colors-14",
      type: "multiple-choice",
      question: "In the phrase 'Rangi ya chungwa', what does 'chungwa' mean?",
      order: 14,
      componentKey: "unit7-multiple-choice",
      contentRef: "activity-colors-14",
    },
  ],
};
