import type { SeedLessonUnit } from "./unit-2";

export const UNIT_4_GREETINGS_SW: SeedLessonUnit = {
  externalId: "unit-4",
  title: "Greetings - Salamu",
  level: "absolute-beginner",
  icon: "👋",
  color: "#FF9800",
  xpReward: 50,
  order: 3,
  isActive: true,
  activities: [
    {
      externalId: "activity-greetings-1",
      type: "introduction",
      question:
        "Welcome! Let's learn how to greet people in Swahili - an essential part of African culture!",
      order: 1,
      componentKey: "greetings-introduction",
      contentRef: "activity-greetings-1",
    },
    {
      externalId: "activity-greetings-2",
      type: "vocabulary-table",
      question: "Basic Greetings",
      order: 2,
      componentKey: "greetings-vocabulary-table",
      contentRef: "activity-greetings-2",
    },
    {
      externalId: "activity-greetings-3",
      type: "vocabulary-table",
      question: "Common Responses",
      order: 3,
      componentKey: "greetings-vocabulary-table",
      contentRef: "activity-greetings-3",
    },
    {
      externalId: "activity-greetings-4",
      type: "multiple-choice",
      question: "How do you say 'Good morning' in Swahili?",
      order: 4,
      componentKey: "greetings-multiple-choice",
      contentRef: "activity-greetings-4",
    },
    {
      externalId: "activity-greetings-5",
      type: "multiple-choice",
      question: "What is the correct response to 'Habari'?",
      order: 5,
      componentKey: "greetings-multiple-choice",
      contentRef: "activity-greetings-5",
    },
    {
      externalId: "activity-greetings-6",
      type: "multiple-choice",
      question: "How do you say 'Thank you very much'?",
      order: 6,
      componentKey: "greetings-multiple-choice",
      contentRef: "activity-greetings-6",
    },
    {
      externalId: "activity-greetings-7",
      type: "multiple-choice",
      question: "What does 'Kwaheri' mean?",
      order: 7,
      componentKey: "greetings-multiple-choice",
      contentRef: "activity-greetings-7",
    },
    {
      externalId: "activity-greetings-8",
      type: "spelling-completion",
      question: "Complete the Spelling of These Greetings",
      order: 8,
      componentKey: "greetings-spelling-completion",
      contentRef: "activity-greetings-8",
    },
    {
      externalId: "activity-greetings-9",
      type: "listening-dictation",
      question: "Listening Exercise: Greetings",
      order: 9,
      componentKey: "greetings-listening-dictation",
      contentRef: "activity-greetings-9",
    },
    {
      externalId: "activity-greetings-10",
      type: "matching",
      question: "Match Greetings to Their Meanings",
      order: 10,
      componentKey: "greetings-matching",
      contentRef: "activity-greetings-10",
    },
    {
      externalId: "activity-greetings-11",
      type: "conversation-practice",
      question: "Practice a Greeting Conversation",
      order: 11,
      componentKey: "greetings-conversation-practice",
      contentRef: "activity-greetings-11",
    },
    {
      externalId: "activity-greetings-12",
      type: "dialogue",
      question: "Meeting Someone New",
      order: 12,
      componentKey: "greetings-dialogue",
      contentRef: "activity-greetings-12",
    },
  ],
};
